# -*- coding: utf-8 -*-
"""Copy of cis540_peft_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0R8Qqpxfb61sotfaQlauJMRO9-5h6TI

# Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch --index-url https://download.pytorch.org/whl/cu128
# %pip install "trl>=0.20.0" "peft>=0.17.0" "transformers>=4.55.0"
# %pip install wandb

# !pip install -U bitsandbytes

"""# Imports"""

import os, json, torch, wandb
from huggingface_hub import login
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig

"""# Config"""

USE_DRIVE = True
DATA_FILE = "/content/drive/MyDrive/instruct_ioc_chat.jsonl"

WANDB_PROJECT = "cis540_final_project"
HF_REPO_ID = "smebellis/apt_threats"

BASE_MODEL = "Qwen/Qwen3-4B-Instruct-2507"

OUTPUT_DIR = "qwen3-4b-ioc-qlora"

"""# Logins"""

print("▶ Login to Hugging Face")
login()
print("✅ Logged in")

print("▶ Login to Weights & Biases (optional)")
try:
    wandb.login()
    os.environ["WANDB_PROJECT"] = WANDB_PROJECT
    print("✅ W&B logged in")
except Exception as e:
    print("W&B login skipped or failed:", e)

if USE_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")

"""# Load Dataset"""

print("▶ Loading dataset from", DATA_FILE)
dataset = load_dataset("json", data_files={"train": DATA_FILE})["train"]
print(dataset[0] if len(dataset) > 0 else "Dataset is empty!")

"""# Tokenizer"""

print("▶ Loading tokenizer")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)

# Ensure there is a proper pad token
if tokenizer.pad_token_id is None or tokenizer.pad_token_id == tokenizer.eos_token_id:
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})

print("▶ Loading base model in 4-bit")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

"""# Prepare Model"""

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="eager",
    torch_dtype=torch.bfloat16
)

model.resize_token_embeddings(len(tokenizer))
model.config.pad_token_id = tokenizer.pad_token_id

"""# LoRA Setup"""

print("▶ Preparing LoRA (QLoRA)")
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules="all-linear",
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

"""# Functions"""

def format_example(example):
    msgs = example.get("messages", None)
    if not msgs:
       raise ValueError("Each sample must have a 'messages' list with role/content.")
    text = tokenizer.apply_chat_template(
        msgs,
        tokenize=False,
        add_generation_prompt=False
    )
    return text



def formatting_func(example):
    return format_example(example)

def quick_generate(prompt_messages, max_new_tokens=128):
    with torch.inference_mode():
        # Step 1: Apply chat template to get the formatted string
        chat_string = tokenizer.apply_chat_template(
            prompt_messages, add_generation_prompt=True, tokenize=False
        )

        encoded_inputs = tokenizer(
            chat_string,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=tokenizer.model_max_length
        )
        # Move inputs to the model's device
        encoded_inputs = {k: v.to(model.device) for k, v in encoded_inputs.items()}

        out = model.generate(
            **encoded_inputs, # Pass the dictionary of tensors
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            repetition_penalty=1.05
        )

        decoded_output = tokenizer.decode(out[0][encoded_inputs['input_ids'].shape[1]:], skip_special_tokens=True)
        return decoded_output

print("▶ Sanity check")
pre_prompt = [
    {"role": "system", "content": "You extract IOCs (SHA256, SHA1, MD5, IPs) in fixed format."},
    {"role": "user", "content": "Sample mentions 209.51.54.243 and hash 35a485972282b7e0e8e3a7a9cfb6ad9385637f8d96ce8e23"}
]
print(quick_generate(pre_prompt)[:800])

"""# Training"""

print("▶ Building trainer and starting training")

training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    bf16=True,
    logging_steps=10,
    save_steps=200,
    save_total_limit=2,
    report_to="wandb",   # or [] to disable
    dataset_num_proc=2,  # preprocess speedup
    packing=False,       # set True if your data are many short samples and you want packing
    push_to_hub=True,    # enable hub push in trainer.save_model()
    hub_model_id=HF_REPO_ID,
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    processing_class=tokenizer,
    formatting_func=formatting_func,
)

trainer.train()

"""# Push to HuggingFace Hub"""

print("▶ Saving model and pushing to Hub…")
trainer.save_model(OUTPUT_DIR)
trainer.push_to_hub()

print("▶ Sanity check (post-train generate)")
print(quick_generate(pre_prompt)[:800])
print("✅ Done")

