# -*- coding: utf-8 -*-
"""Inference_cis540.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBTZRg3gBz5qobd6zDr0ay4dAFL7J5h2

# Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch --index-url https://download.pytorch.org/whl/cu128
# %pip install "trl>=0.20.0" "peft>=0.17.0" "transformers>=4.55.0"
!pip install -U bitsandbytes

"""Import"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

MODEL_PATH = "smebellis/apt_threats2"

"""# Load Tokenizer"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, use_fast=True)



"""# Load Base Model"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

base_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen3-4B-Instruct-2507",  # same base model used for training
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)
# Resize token embeddings to match the tokenizer's vocabulary size
base_model.resize_token_embeddings(len(tokenizer))

model = PeftModel.from_pretrained(base_model, MODEL_PATH)
model.eval()

"""# Helper Function to Generate Prediction"""

def generate_iocs(prompt_text, max_new_tokens=256):
    messages = [
        {"role": "system", "content": "You are a cyber threat intelligence model trained to extract IOCs."},
        {"role": "user", "content": prompt_text}
    ]
    # First, get the formatted chat string. tokenize=False ensures it returns a string.
    formatted_chat = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False
    )
    # Then, tokenize the formatted string to get a BatchEncoding object (dictionary of tensors).
    enc = tokenizer(
        formatted_chat,
        return_tensors="pt",
        padding=True,
        truncation=True
    )
    enc = {k: v.to(model.device) for k, v in enc.items()}

    with torch.inference_mode():
        out = model.generate(
            **enc,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            repetition_penalty=1.05
        )
    return tokenizer.decode(out[0], skip_special_tokens=True)

"""# =======Example Usuage=========="""

example_text = """
APT group: APT1 / Comment Crew\n\nList all known indicators of compromise (IOCs) in structured format.

"""

print("=== Inference Output ===")
print(generate_iocs(example_text))

